* Functions to remember
** Prelude
enumFromTo
enumFromThenTo
reverse
show :: Show a => a -> String
flip
sequence - Evaluate each monadic action in the structure from left to right, and collect the results.
:sprint - show variables to see what has been evaluated already.
minBound - smaller bound
maxBound - larger bound
*** Ord
compare
*** Calc
div - always makes rounding down, to infinity
divMod - returns a tuple containing the result of integral division and modulo 
*** List operations
concat - [ [a] ] -> [a]
elem x xs - is element a part of a list
zip :: [a] -> [b] -> [(a, b)] - zips two lists together. Zip stops when one list runs out.
zipWith :: (a -> b -> c) -> [a] -> [b] -> [c] - do the action on corresponding elements of list and store in the new list
** Data.List
intersperse :: a -> [a] -> [a]  -  gets the value and incerts it between values in array
nub - remove duplicates from the list
** Data.Char
ord (Char -> Int)
chr (Int -> Char)
isUpper (Char -> Bool)
toUpper (Char -> Char)
** QuickCheck
quickCheck :: Testable prop => prop -> IO ()

quickCheck . verbose - run verbose mode
* Debugger

Provides:
  * set a breakpoints
  * observe step-by-step evaluation
  * tracing mode

** Commands
:list

** Breakpoints 
:break 2
  :show breaks
  :delete 0
:continue

** Step-by-step
:step main
** What been evaluated already
:sprint name
* FunFunc
cycle :: [a] -> [a] - indefinitely cycle s list
repeat - indefinit lis from value
elemIndex e l - return first index, returns Maybe
fromMaybe (default if Nothing) e ::Maybe a -> a
lookup :: Eq a => a -> [(a, b)] -> Maybe b
* Good code
Use data type aliases to deferentiate logic of values.

Unconstrained means most flexible, but the most useless.
The more constrained system has more usefulness.

*** Read Conventions of variables (page 176)
*** Wideness of polymorphism
Parametric polymorphism is broader then constrained polymorphism
*** Damas–Hindley–Milner type system
*** Print
print :: Show a => a -> IO ()
print a = putStrLn (show a)
*** Read code evaluation (488 on-ward)
*** Fold
foldr spine recursion intermediated by the folding
foldl spine folding is unconditional, then solding starts.

So foldr can terminate at any point, while foldl unconditionally recurses across the spine, even if it infinite.
*** Computation model
Model the domain and types before thinking about how to wriet computations.
*** Make bottoms only local
*** Newtype wrap is ideally transparent for compiler and does not change performance
*** Instances of types/type classes must go with code you write
*** Functions can be abstracted as arguments
*** Infix operators can be bind to arguments
*** Arbitrary
Product types can be tested as a product of random generators.
Sum types require to implement generators with separate constructors, and picking one of them, use `oneof` or `frequency` to pick generators.

*** Principle of Separation of concerns
*** Function composition
In Haskell inline composition requires:
#+begin_src haskell
h.g.f $ i
#+end_src
Function application has a higher priority than composition. That is why parentheses over argument are needed.
This precedence allows idiomatically compose partially applied functions.

But it is a way better then:
#+begin_src haskell
h (g (f i))
#+end_src
*** Functor application
Function application on n levels beneath:
#+begin_src haskell
(fmap.fmap) function twoLevelStructure
#+end_src

How fmap.fmap typechecks:
#+begin_src haskell
(.) :: (b -> c) -> (a -> b) -> a -> c
fmap :: Functor f => (m -> n) -> f m -> f n
fmap :: Functor g => (x -> y) -> g x -> g y

(.) :: (Functor f, Functor g) => ((g x -> g y) -> f.g (x) -> f.g (y))
                                      -> ((x -> y) -> g x -> g y)
                                      -> (x -> y) -> f.g (x) -> f.g. (y)
fmap.fmap :: (x -> y) -> f.g (x) -> f.g. (y)
#+end_src
*** Paramenter order
In functions parameter order is important.
It is best to use first the most reusable parameters.
And as last one the one that can be the most variable, that is important to chain.
* Definitions
** Abstraction
Generalization of process from concrete instance of a problem mainly by introduction of names.
** Actual type
[[Data type]] recieved by execution.
** Alpha equivalence
If names of parameters in [[Expression][expressions]] accordingly different, but process is literally the same - that means that names are synonyms and [[Expression][expression]] are alpha equivalent.
** Anamorphism
Morphism from a coalgebra to the final coalgebra for that endofunctor
** Anonymous function
Lambda function without the name to bind to.
** Application
For FP see [[Bind]]. And then [[Beta reduction][beta reduction]] happen
** Argument
Is an input value to a function.
** Arity
Number of parameters of the function.
  * nullary - f()
  * unary   - f(x)
  * binary  - f(x,y)
  * ternary - f(x,y,z)
  * n-ary   - f(x,y,z..)
** As-pattern
f list@(x, xs) =
** Base case
A part of a [[Recursion][recursive]] [[Function][function]] that produces result trivially.
** Beta normal form
No [[Beta reduction][beta reduction]] is possible
** Beta reduction
Applying [[Function][function]] to an [[Argument][argument]].
** Binary tree
#+begin_src haskell
data BinaryTree a =
    [[Leaf]]
  | [[Node]] (BinaryTree a) a (BinaryTree a)
  deriving (Eq, Ord, Show)
#+end_src
** Bind
Eq between two objects.
Parameter of the function = argument that applied to the function
Variables = values.
** Bottom value
#+begin_src haskell
-- _ fits *.
#+end_src

Is a non-value used to denote the program cannot return a values.
** Cardinality
Number of elements.

Number of possible implementations for a given type signature.

On sum - add cardinalities.
On product - multiply cardinalities.
** Catamorphism
(from the Greek: κατά "downwards" and μορφή "form, shape") denotes the unique homomorphism from an initial algebra into some other algebra.

In functional programming, catamorphisms provide generalizations of folds of lists to arbitrary algebraic data types, which can be described as initial algebras. The dual concept is that of anamorphism that generalize unfolds. A hylomorphism is the composition of an anamorphism followed by a catamorphism.
** Combinator
Lambda term without free variables.

Higher-order [[Function][function]] that uses only function application and earlier defined combinators to define a result from its arguments.

Narrow meaning: A function or definition with no free variables.

Informal broad meaning: referring to the style of organizing libraries centered around the idea of combining things.
** Compose
See: [[Function composition]]
** Concatenate
Link together sequences.
** Concrete type
** Cons
Short for [[Construct]].
** Cons cell
Cell that values may inhabit.
** Constant
Nullary constructor
** Constrain
See: [[Ad hoc polymorphism]]
** Construct
#+begin_src haskell
(:) :: a -> [a] -> [a]
#+end_src
** Constructor
1. [[Type constructor]]
2. [[Data onstructor]]

Also see: [[Constant]]
** Currying
Translating the [[Evaluation][evaluation]] of a multiple [[Argument][argument]] function (or a tuple of arguments) into evaluating a sequence of [[Function][functions]], each with a single argument.
** Data constant
See: [[Constant]]
** Data constructor
One instance that [[Inhabit][inhabit]] [[Data type][data type]].

Constant value - nullary data constructor.
** Data declaration
[[Data type]] definition.
** Data type
Data type, type.
*** Algebraic data type
Composite type formed by combining other types.
*** Higher-kinded data type
Any combination of * and ->

Type that take more types as arguments.
*** Product data type
Logical conjunction.
A data type that consists of AND areas.
*** Sum data type
Logical disjunction.
A data type that consists of OR areas.
** Declaration
Top-level [[Bind][bindings]] which allow us to name [[Expression][expressions]].
** Derived instance
Type classes such as Eq, Enum, Ord, Show can have instances generated based definition of data type.
** Dispatch
Send, transmission, reference.
** Effect
Observable action.
** Evaluation
For FP see [[Bind]].
** Expected type
[[Data type]] infered from the text of the code.
** Expression
Finite combination of a symbols that is well-formed according to rules that depend on the context.
** First-class
1. Can be used as [[Value][value]].
2. Passed as an [[Argument][argument]].
** Fold
Higher-order function ruturns accumulated result from recursive data structure applying a function.
** Free variables
Variables in the fuction that is not bound by the head.
They live empty and fuction as so is not fully applied.
** Function
Idealization of how a varying quantity depends on another quantity.

$x \in X, y \in Y : f^{X \to Y} = \overset{\rightharpoonup}{G}(x,y)$

Directionality and property of invariability emerge from one another.
#+begin_src haskell
   *      ->   *
-- domain func codomain
#+end_src

Function is a mathematical [[Operation][operation]].

Function = Total function = Pure function. Function theoretically posible to momoized.
[[Partial function]].
Inverse function - often partially exists (partial function).
** Function body
[[Expression]] that haracterizes the process.
** Function head
Is a part with Name of the [[Function][function]] and it's [[Parameter][paramenter]].
AKA: f(x)
** Higher-order function
Function arity > 1.

----

A) Has function as an argument.
B) Evaluates to function.
** HOF
See: [[Higher-order function]]
** Identity function
Return itself.
(\x.x)
#+begin_src haskell
id :: a -> a
#+end_src
** Partial function
Does not cover all cases.
Unsafe and causes trouble.
** Function composition
#+begin_src haskell
(.) :: (b -> c) -> (a -> b) -> a -> c

a -> (a -> b) -> (b -> c) -> c
#+end_src

In Haskell inline composition requires:
#+begin_src haskell
h.g.f $ i
#+end_src
** Infix
Operaton in-between variables.
** Inhabit
What [[Values][values]] inhabit [[Data type][data type]]
** Interface
Point of mutual meeting. Code behind interface determines how data is consumed.
** IO
Type for values whose evaluations has a posibility to cause side effects.
** Kind
Kind -> Type -> Data
** Lambda calculus
Universal model of computation that can be used to simulate any Turing machine.
Based on [[Function][function]] [[Abstraction][abstraction]] and application using variable [[Bind][binding]] and substitution.
** Leaf
 _
** Left associative
Same level [[Exression][expression]] parts in reality follow grouping from left to right.
(\x.x)(\y.y)z = ((\x.x)(\y.y))z
** Level of code
There are mainly three levels of Haskell code.
- [[Type level]]: part that works with [[Data type][data types]]
- [[Term level]]: logical execution part of the code
- Compile level: level when code compiles/compiled
** Lexical scope
Scope search sourcecode blocks structure determined.
** Local
[[Scope]] applies only in an area
** Module
Importable organization unit.
** Modulus
Modular arithmetic is a system of arithmetic for integers where number wraps around upon reacing a modulus.
** Monomorphic
Made of one form.
** Node
 *
/ \
** Normal form
In context: [[Beta normal form]]
** Nothing
Any Haskell expression can't return nothing.
** Operator
[[Infix]] [[Function][function]].
** Parameter
Or Formal Parameter - named varible of a [[Function][function]].
** Partial application
Part of [[Function][function]] [[parameter][parameters]] [[Application][applied]].
** Pointfree
Point-free style, or Tacit programming is a paradigm in which function definition does not notate arguments. Instead definitions merely compose other functions.
** Polymorphism
At once several forms.

To [[Abstraction][abstract]] over [[Data types][data types]].


/Antonym - [[Monomorphism]]./

Types:
*** Levity polymorphism
Levity polymprphism is when polymorphism works with lifted and [[Unlifted type][unlifted types]].
*** Parametric polymorphism
[[Abstraction][Abstracting]] over [[Data type][data types]] by [[Parameter][parameter]].

/In most languages named as 'Generics' (generic programming)./

Types:
**** Let-bound polymorphism
It is property chosen for Haskell type system.
Haskell is based on Hindley-Milner type system, it is let-bound.
It means that to have strict type inference - if `let` and `where` declarations a polymorphic - $\lambda$ declarations - should be not.
So:
#+begin_src haskell
foo :: (Int, Char)
foo = (\f -> (f 1, f 'a')) id
#+end_src
Is illigal in Haskell.

Lambda-bound function (i.e., one passed as argument to another function) cannot be instantiated in two different ways, if there is a let-bound polymorphism.
**** Constrained polymorphism
Constrained [[Parametric polymorphism]].
**** First-class polymorphism
More default term: [[Impredicative polymorphism]].
**** Impredicative polymorphism
The most powerful form of [[Parametric polymorphism]].
First see [[Impredicative]].

Impredicative polymorphism allows type τ entities with polymorphic types, that can contain type τ itself.
$T \in T, T = \forall X. X \to X: T \in X$
This approach has Russell's paradox (and its form - Girard's paradox).
*** Ad hoc polymorphism
Artificial [[Polymorphism][polymorphism]] dependent on incoming [[Data type][data type]].
Achieved by creating a [[Type class][type class]] [[Function][functions]].
It is interface dispatch mechanism by data types.

/Commonly known as overloading./
*** Subtype polymorphism
Allows to declare usage of a Type and all of its Subtypes.
T - Type
S - Subtype of Type
<: - subtype of
$S <: T = S \le T$

Subtyping is:
If it can be done to T, and there is subtype S - then it also can be done to S.
$S <:T, f^{T \to X} \Rightarrow f^{S \to X}$
*** Row polymorphism
# NOTE: 2019-03-11: Currently WIP in https://github.com/ghc-proposals/ghc-proposals/pull/180 
Is a lot like Subtype polymorphism, but alings itself on allowence (with | r) of subtypes and types with requested properties.
#+begin_src haskell
printX :: { x :: Int | r } -> String
printX rec = show rec.x

printY :: { y :: Int | r } -> String
printY rec = show rec.y

-- type is inferred as `{x :: Int, y :: Int | r } -> String`
printBoth rec = printX rec ++ printY rec
#+end_src
*** Kind polymorphism
Achieved using a phantom type argument in the data type declaration.
#+begin_src haskell
;;         * -> *
data Proxy a = ProxyValue
#+end_src
Then, by default the data type can be inhabited and fully work being partially defined.
But multiple instances of kind polymorphic type can be distinguished by their particular type.

Example is the [[Proxy type]]:
#+begin_src haskell
data Proxy a = ProxyValue

let proxy1 = (ProxyValue :: Proxy Int) -- * :: Proxy Int
let proxy2 = (ProxyValue :: Proxy a)   -- * -> * :: Proxy a
#+end_src

*** Higher-rank polymorphism
Means that polymorphic types can apper within other types (types of funtion).
There is a cases where higher-rank polymorphism than the a Ad hoc - is needed. For example where ad hoc polymorphism is used in constraints of several different implementations of functions, and you want to build a function on top - and use the abstract interface over these functions.
#+begin_src haskell
-- ad-hoc polymorphism
f1 :: forall a. MyType Class a => a -> String
f1 = -- ...

-- higher-rank polymorphism
f2 :: Int -> (forall a. MyType Class a => a -> String) -> Int
f2 = -- ...
#+end_src
By moving `forall` inside the function - we can achive higher-rank polymorphism.

From: https://news.ycombinator.com/item?id=8130861
#+begin_src text
Higher-rank polymorphism is formalized using System F, and there are a few implementations of (incomplete, but decidable) type inference for it - see e.g. Daan Leijen's research page [1] about it, or my experimental implementation [2] of one of his papers. Higher-rank types also have some limited support in OCaml and Haskell.
#+end_src

Useful example aslo a [[ST-Trick monad]].
*** Linearity polymorphism
Leverages [[Linear type][linear types]].
For exampe - if fold over a dynamic array:
  1) In basic Haskell - array would be copied at every step.
  2) Use low-level unsafe functions.
  3) With Linear type function we guarantee that the array would be used only at one place at a time.

So, if we use a function (* -o * -o -o *) in foldr - the fold will use the initial value only once.
** Impredicative
Self-referencing definition.

---

/Antonym - [[Predicative]]./
** Predicative
Non-self-referencing definition.

---

/Antonym - [[Impredicative]]./
** Principal type
The most generic [[Data type][data type]] that still typechecks.
** Purity
[[Referantial transparency][Referential transparent]] [[Function][function]]
** Recursion
Repeated function application allow computing results that may require indefinite amount of work.
** Redex
[[Reduction][Reducible]] [[Expression][expression]]
** Reduction
See [[Beta Reduction]]
** Referential transparency
Function returns the same output given the same values to evaluate.

[[Expression]] is referentially transparent if can be replaced with its corresponding resulting value without change for program's behavior.
Such [[Functions][functions]] are called [[Pure][pure]].
** REPL
Interactive CLI. Read-eval-print loop.
** Scope
Area where [[Bind][bind]] is accessible.
** Sectioning
Writing [[Function][function]] in a parentheses. Allows to pass around [[Partial application][partially applied]] [[Function][functions]].
** Shadowing
Global scope variable overriden by variable in local scope.
** Smart constructor
Place extra constraints on the construction of values.
** Spine
#+begin_src text

  :
 / \
1   :
   / \
  2   :
     / \
    3  []

1:2:3:[]

  :
 / \
_   :
   / \
  _   :
     / \
    _  []

#+end_src
** Statement
Declarative sentence that is true or false.
Gonzales: "What code does."
** Static typing
Static typechecking occurs at [[Level of code][compile time]]
** Superclass
Broader parent class.
** Syntatic sugar
Artificial way to make language easier to read and write.
** Tail call
Final result of the function
** Tail recursion
Tail calls are recursive invocantions of itself.
** Term level
See: [[Level of code]]
** Tuple
Data type that stores multiple values withing a single value.
Tuples by [[Arity][arity]]:
  * empty, [[Unit][unit]]          - 0
  * pair, two-tuples     - 2
  * thriple, three-tuple - 3
** Type
Type - [[Set][set]] of values.
See [[Data type]]
** Type alias
Create type constructor, not data constructor.
** Set
Well-defined collection of distinct objects.
** Type constant
See: [[Constant]]
** Type constructor
Name of [[Data type][data type]]

Nullary type constructor is [[Type constant]]
** Type inference
Automatic [[Data type][data type]] detection of [[Expresion][expression]].
** Type level
See: [[Level of code]]
** Type variable
Refer to an unspecified type in Haskell type signature.
** Type class
Type system construct that adds a support of [[Ad hoc polymorphism][ad hoc polymorphism]].
** Type class inheritance
[[Type class]] has a [[Superclass][superclass]]
** Type instance
Unique [[Type class][type class]]->[[Data type][type]] pairing.
Defines type class->type methods.
** Uncurry
Replace number of [[Function][functions]] with [[Tuple][tuple]] of number of values
** Undefined
Value helps to do typechecking
** Unit
Value, [[Data type][type]]. Represents nothing. Empty [[Tuple][tuple]]
** Unsafe
[[Function]] that does not cover some edge case.
** Variable
A name for [[Expression][expression]].

Haskell has immutable variables.
Except when you hack it with explicit [[Function][funсtions]].
** Variadic
Variadic funtion has a indefinite [[Arity][arity]]. Assepts a variable number of [[Argument][arguments]].
** Associative law
$\forall (a,b,c) \in S : P(a,P(b,c))=P(P(a,b),c)$,
Etymology:
Joined by a common purpose.
Latin /associatus/ past participle of /associare/ "/join with/", from assimilated form of /ad/ "/to/" + /sociare/ "/unite with/", from /socius/ "/companion, ally/" from PIE /*sokw-yo-/, suffixed form of root /*sekw-/ "/to follow/".
** Monoid
[[Semigroup]] that has [[Identity]] value.

#+begin_src haskell
class Monoid m where
mempty :: m
mappend :: m -> m -> m
mconcat :: [m] -> m
mconcat = foldr mappend mempty
#+end_src
*** Abelian or commutative monoid
Very helpful at concurrent or distributed processing.
*** Monoid laws
#+begin_src haskell
-- left identity
mappend mempty x = x
-- right identity
mappend x mempty = x
-- associativity
mappend x (mappend y z) = mappend (mappend x y) z
mconcat = foldr mappend mempty
#+end_src
** Binary
Two of something.
** Operation
As also called [[Function][function]].
Used in mathematics. Word often used for [[Infix][infix]] operations.
** Identity
*** Two-sided identity of a [[Predicate][predicate]]
$P()$ is [[Commutative][commutative]].
$\exist e \in S, \forall a \in S : P(e,a)=P(a,e)=a$
*** Left identity of a [[Predicate][predicate]]
$\exist e \in S, \forall a \in S : P(e,a)=a$
*** Right identity of a [[Predicate][predicate]]
$\exist e \in S, \forall a \in S : P(a,e)=a$

Identity only possible with morphism.
There is also a distinct [[Zero]] value.
** Predicate
[[Assertion]] includes variable.
Notation: $P(x)$
[[Application]] of [[Argument][argument]] results in true or false predicate.
** Assertion
Statement.
Утверждение.
** Commutative law
$\forall (a,b) \in S : P(a,b)=P(b,a)$
** Conjunction
AND
** Disjunction
OR
** Orphan type instance
[[Type instance]] that appeared from inconsistent code base. Duplicate of instance, or instance present on [[Type class][type class]] or on [[type]] level.

Solution for addressing orphan instances:
1. You defined the type but not the type class?
Put the instance in the same module as the type so that the type cannot be imported without its instances.
2. You defined the type class but not the type?
Put the instance in the same module as the type class definition so that the type class cannot be imported without its instances.
3. Neither the type nor the type class are yours?
Define your own newtype wrapping the original type and now you’ve got a type that “belongs” to you for which you can rightly define type class instances. There are means of making this less annoying which we’ll discuss later.
** Semigroup
$\forall (a,b,c) \in S : P(a,P(b,c))=P(P(a,b),c)$

Semigroup - a set (S) with a binary operation (P) and [[Associative law][associative law]].
Semigroup is closed (forms a closed set).
A [[Magma]] with associative law.

Defined in Haskell as:

#+begin_src haskell
class Semigroup a where
(<>) :: a -> a -> a
#+end_src

** Magma
Set with a single binary operation.

The category of magmas, denoted $Mag$, has as objects sets with a binary operation, and morphisms given by homomorphisms of operations (in the universal algebra sense).
** Binary operation
$\forall (a,b) \in S, \exists P(a,b)=f(a,b): S \times S \to S$
** data declaration
[[Data type]] declaration is the most general and versatile form to create a new data type.
Form:
#+begin_src haskell
data [context =>] type typeVars1..n
  = con1  c1t1..i
  | ...
  | conm  cmt1..q
  [deriving]
#+end_src haskell
** type declaration
Synonim for existing type. Uses the same data constructor.
#+begin_src haskell
type FirstName = String
#+end_src haskell
Used to distinct one entities from other entities, while they have the same type.
Also main type functions can operate on a new type.
** newtype declaration
Creates a new type from old type using a new constructor.
#+begin_src haskell
newtype FirstName = FirstName String
#+end_src haskell

Data will have exactly the same representation at runtime, as the type that is wrapped.

#+begin_src haskell
newtype Book = Book (Int, Int)
#+end_src haskell
#+begin_src text
      (,)
      / \
Integer Integer
#+end_src
** Gen type
Generator. List it returns gets infinitely cycled.
** Arbitrary type class
[[Type class]] of [[QuickCheck]].Arbitrary (that is reexported by QuickCheck) for creating a generator/distribution of values.
Useful function is arbitrary - that autoassumes/generates values.
** Arbitrary function
Depends on type and generates values of the type.
** NonEmpty list data type
Data.List.NonEmpty
Has a Semigroup instance but can't have a Monoid instance. It never can be an empty list.

#+begin_src haskell
data NonEmpty a = a :| [a]
  deriving (Eq, Ord, Show)
#+end_src haskell

:| - an infix data costructor that takes two (type) arguments. In other words :| returns a product type of left and right
** Category
Category (/C/) consists of:
  1. Objects - ob(/C/). Sets.
  2. Morphisms - C(a,b), hom(a,b). Mappings, total functions.
  3. Binary operation "Composition of morphisms": $\forall a, b, c: C(a, b) \circ C(b, c) \to C(a, c)$
  4. Axiom of [[Associative law][Associativity]]: $f_{a \to b}, g_{b \to c}, h_{c \to d} : h \circ (g \circ f) = (h \circ g) \circ f$.
  5. Axiom of two sided [[Identity]] of morphisms: $\forall x  \exists  id_{x : x \to x},  \forall f_{a \to x},  \forall g_{x \to b}  :  id_x \circ f_{a \to x} = f_{a \to x}, g_{x \to b} \circ id_x = g_{x \to b}$ (both left and right identity)

From these axioms, one can prove that there is exactly one identity morphism for every object.
** Semantics
Philosophical study of meaning.
** Principle of compositionality
The meaning of a complex [[Expression][expression]] is determined by the meanings of its constituent expressions and the rules used to combine them.
** Operational semantics
Properties, such as correctness, safety or security, are verified by constructing proofs from logical [[Assertion][statements]] about execution and procedures.

Good to solve in-point localized tasks.
Process of abstraction.
** Denotational semantics
Constructing mathematical objects (called denotations) that describe the meanings.

Good to achive more broad approach/meaning.
Process of modelling.
** Axiomatic semantics
Describing effect of operation on assertions about the overall state.

Good for examining interconnections.
Empirical process.
** SET category
Category in which objects are sets.
** Relation
Is not directed and not limited.
** Cartesian product
${\forall a \in A, \forall b \in B : A \times B = \overset{\rightharpoonup}{(a,b)}}$.
Any function is a subset of Cartesian product.
** Fundamental theorem of algebra
Any non-constant single-variable polynomial with complex coefficients has at least one complex root.
Also derives that the field of complex numbers is algebraically closed.
** Isomorphism
AKA bijective [[Morphism][morphism]]. Morphism that has inverse morphism.
$f^{-1, b \to a} \circ f^{a \to b} = id_a, f^{a \to b} \circ f^{-1, b \to a} = id_b$

2 reasons for non-isomorphic function:
- function at least ones collapses a values of domain into one value in codomain
- image (of a function in codomain) does not fill-in codomain. Then isomorphism can exists for image but not whole codomain.
** Morphism
[[Function]]
** IO ()
Pure programming language uses `IO ()` for functions that for the same circumstances in the code space - can return a different result.
** CoArbitrary
Pseudogenerates a function basing on resulting type.
#+begin_src haskell
coarbitrary :: CoArbitrary a => a -> Gen b -> Gen b
#+end_src
** Idempotence
After the initial application operation can be applied multiple times without changing the result.
Example: Start and Stop buttons on machines. 
** Monomorphism
Initial set of /f/ is fully one-to-one (uniquely) mapped into the image of /f/.
Left is mono (uniquely) mapped to the right, so left domain can be equal or less to the right codomain.
It is injective.
It always has a inverse morphism.
** Epimorphism
Image of a function /f/ is fully used - epimorphism.
Left is epi to the right. So left is bigger or equal then the right. And right is a projection of the left.
It is surjective.
** Closed set
Closed set - a set whose complement is an open set.
Closed set is a form of [[Closed-form expression]]. Set can be closed in under a set of operations.
** Closed-form expression
Closed-form expression - a mathematical expression that can be evaluated in a finite number of operations. It may contain constants, variables, certain "well-known" operations (e.g., + − × ÷), and functions (e.g., nth root, exponent, logarithm, trigonometric functions, and inverse hyperbolic functions), but usually no limit.
** Closure
Set has closure under an operation if performance of that operation on members of the set always produces a member of the same set; in this case we also say that the set is closed under the operation.
** Algebra
1) Abstract algebra - the study of number systems and operations within them.
2) Algebra - vector space over a field with a multiplication.
** Functor
Functor is a map between categories.

#+begin_src haskell
class Functor f where
  fmap :: (a -> b) -> f a -> f b
#+end_src
Functor is a type class for function application "over/through" ignored/untouched structure f.
Functor abides [[Functor laws]].
** Functor laws
Type instance of functor should abide this laws:
1. Identity law
#+begin_src haskell
fmap id == id
#+end_src
2. Composition law
#+begin_src haskell
fmap (f.g) == fmap f . fmap g
#+end_src
In words, it is if several functions are composed and then fmap is applied on them - it should be the same as if functions was fmapped and then composed.
** Lift
Lift is to do a function application through the data structure.
** Idiom
Idiom - something having a meaning that cannot be derived from the conjoined meanings.
Meaning can be special for language speakers or human with particular knowledge.
** Idiomatic
See [[Idiom]].
** Function application
Function application is applying the function to an argument from its domain to obtain the resulting value from its range.
** Function range
The range of a function refers to either the codomain or the image of the function, depending upon usage. Modern usage almost always uses range to mean image.
So, see [[Function image]].
** Combinator
A function or definition with no free variables.
** Codomain
Codomain - target set of a function in $X \to Y$.
** Hindley–Milner (HM) type system
Classical type system for the [[Lambda calculus]] with [[Parametric polymorphism]] and [[Type inference]].
Where types marked as polymorphic variables, and overall type inference is possible all over the code.
Also known as Damas–Milner or Damas–Hindley–Milner system.
** Singleton
Singleton - unit set - set with exactly one element.
Also 1-tuple.
** Initial object
Initial object - is an object I in category C: $\exists I \in C: \forall X \in C, \exists ! (I \to X)$.
** Terminal object
Terminal object - is an object I in category C: $\exists I \in C: \forall X \in C, \exists ! (X \to I)$.
** Pragma
Pragma - instruction to the compiler placed in the source code that specifies how a compiler should process the code.
Pragma in Haskell have form:
#+begin_src haskell
{-# PRAGMA options #-}
#+end_src
** Pragma option
Values supplied to the [[Pragma]] directive.
** Language option
Language option - control what variations of the language are permitted.
It has a set of allowed values: https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html, which can be supplied to Language [[Pragma]].
** Identity morphism
Identity morphism - or simply identity: $x \in C : id_{x}=1_{x} : x \to x$
Composed with other morphism gives same morphism.
** Shrinking
Process of reducing coplexity in the test case - re-run with smaller values and make sure that the test still fails.
** Zero
Zero is the value operation with which always gives Zero value.
$n, zero \in C : \forall n, zero*n=zero$
There is also distinct [[Identity]] value.
** Proxy type
Proxy type holds no data, but has a phantom parameter of arbitrary type (or even kind). Able to provide type information, even though has no value of that type (or it can be may too costly to create one).
#+begin_src haskell
data Proxy a = ProxyValue

let proxy1 = (ProxyValue :: Proxy Int) -- a has kind `Type`
let proxy2 = (ProxyValue :: Proxy List) -- a has kind `Type -> Type`
#+end_src
** Structural type
Is a type in the real mathematical sence, in the Structural Type System.
The Structural Type System differentiate and compares the types basing on their properties. So all structural types have a global hierarchy of properties, types and subtypes.
Like in Haskell.
In most languages typing is not structural - but name-based.
** Linear type
Type system and algebra that also track the multiplicity of data.
There are 3 general linear type groups:
 * 0 - exists only at type level and is not allowed to be used at value level. Aka `s` ins ST-Trick.
 * 1 - data that is not duplicated
 * 1< - all other data, that can be duplicated multiple times.

Linear types are great to control/minimize resource usage.
** Unlifted type
Type that directly exist on the hardware. The type abstraction can be completely removed.
With unlifted types Haskel type system directly manages data in the hardware.
** Lambda cube
λ-cube shows the dimentions of generalization from simply typed [[Lambda calculus]] to [[Calculus of constructions]].

Each dimension of the cube corresponds to a new way of making objects depend on other objects:
  * ([[First-class polymorphism]]) - terms allowed to depend on types, corresponding to polymorphism.
  * ([[Higher-order polymorphism]]) - types depending on terms, corresponding to dependent types.
  * ([[Type class]]) - types depending on types, corresponding to type operators.
* Investigate
** Control.monad
* Citations:
"One of the finer points of the Haskell community has been
its propensity for recognizing abstract patterns in code which
have well-defined, lawful representations in mathematics." (Chris Allen, Julie Moronuki - "Haskell Programming from First Principles" (2017))
* TeX examples
$\displaystyle L(f,P)=\sum_{i=0}^{n-1} inf_{t\in[x_i,x_{i+1}]}f(t)(x_{i+1}-x_{i})$,

\begin{equation}
x=\sqrt{b}
\end{equation}

If $a^2=b$ and \( b=2 \), then the solution must be
either $$ a=+\sqrt{2} $$ or \[ a=-\sqrt{2} \].
* Tools
** Search over the Haskell packages code: Codesearch from Aelve
https://codesearch.aelve.com/
* Libs
** Parsers - megaparsec
** CLIs - optparse-applicative
** HTML - Lucid
** Web applications - Servant
* Misc




