#+STARTUP: latexpreview
#+STARTUP: entitiespretty
* Definitions
** Abelian category
Is which:
  * has a zero object,
  * has all binary biproducts,
  * has all [[Kernel][kernel]]s and cokernels,
  * (it has all pullbacks and pushouts)
  * all [[Monomorphism][monomorphism]]s and [[Epimorphism][epimorphism]]s are normal.
Abelian [[Category][category]] are very stable; for example they are regular and they satisfy the snake lemma.
The class of Abelian categories is closed under several categorical constructions.
** Abstraction
abs away from, off (in absentia)
tractus draw, haul, drag


Purified generalization of process.
It is great did to name an abstraction ([[Denotational semantics]]).
** Actual type
[[Data type]] recieved by ->[[Type inference][inferring]]->compiling->execution.
** Algebra
al-jabr - assemble parts.
A system of algebra based on given axioms.

---

1) Abstract algebra - the study of number systems and operations within them.
2) Algebra - vector space over a field with a multiplication.
** Alpha equivalence
Alpha equivalence - in [[Expression][expressions]] process is literally the same, but names of parameters accordingly different (then they are synonyms).
** Ambigram
Object which from different points of view has different projections. Thou from projections only partial understanding of object is drawn.

While this word has two contradictory meaning, one was chosen.
** Anamorphism
[[Morphism]] from a [[Coalgebra][coalgebra]] to the final coalgebra for that [[Endofunctor][endofunctor]].
Is a [[Function][function]] that generates a sequence by repeated [[Application][application]] of the function to its previous result.
** Application
For FP see [[Bind]]. And then [[Beta reduction][beta reduction]] happen.
** Application memory
| Storage of                        | Block name    |
|-----------------------------------+---------------|
| All not currently processing data | Heap          |
| Function call, local variables    | Stack         |
| Static and global variables       | Static/Global |
| Instructions                      | Binary code   |

When even Main invoked - it work in Stack, and called Stack frame. Stack frame size for function calculated when it is compiled.
When stacked Stack frames exceed the Stack size - stack overflow happens.
*** Heap
See [[Application memory]].
*** Stack
See [[Application memory]].
** Applicative
See [[Applicative functor]] for [[Category theory]] description.
Sequencing functorial computations.

#+begin_src haskell
(<*>) :: f (a -> b) -> f a -> f b
#+end_src

Requires [[Functor]] to exist.
Requires [[Monoid][Monoidal]] structure. And has structure rules, that are separate from what happens inside it.
Structure goes through Monoidal process.

[[Data type]]s can have several applicative implementations.
*** Applicative laws
**** Identity law
#+begin_src haskell
pure id <*> v = v
#+end_src
**** Composition law
Function composition works regularly.
#+begin_src haskell
pure (.) <*> u <*> v <*> w = u <*> (v <*> w)
#+end_src
**** Homomorphism law
Applying the function doesn't change the structure around values.
#+begin_src haskell
pure f <*> pure x = pure (f x)
#+end_src
**** Interchange law
On condition that internal order of evaluation is preserved - order of operands is not relevant.
#+begin_src haskell
u <*> pure y = pure ($ y) <*> u
#+end_src

*** Special applicatives
**** Identity applicative
#+begin_src haskell
-- Applicative f =>
-- f ~ Identity
type Id = Identity
instance Applicative Id
  where
    pure :: a -> Id a
    (<*>) :: Id (a -> b) -> Id a -> Id b

mkId = Identity
xs = [1, 2, 3]

const <$> mkId xs <*> mkId xs'
-- [1,2,3]
#+end_src
**** Constant applicative
It holds only to one value. The function does not exist and `b` is phantom.
#+begin_src haskell
-- Applicative f =>
-- f ~ Constant e
type C = Constant
instance Applicative C
  where
    pure :: a -> C e a
    (<*>) :: C e (a -> b) -> C e a -> C e b

pure 1
-- 1
pure 1 :: Constant String Int
-- Constant {getConstant = ""}
#+end_src

**** Maybe applicative
"There also can be no function at all."

If function might not exist - embed `f` in Maybe structure, and use Maybe applicative.
#+begin_src haskell
-- f ~ Maybe
type M = Maybe
pure :: a -> M a
(<*>) :: M (a -> b) -> M a -> M b
#+end_src
**** Either applicative
`pure` is `Right`.
Defaults to `Left`.
And if there is two Left's - to Left of the first argument.
**** Validation applicative
The Validation data type isomorphic to Either, but has accumulative Applicative on the error side.
For this Applicative there is no corresponding Bind or Monad instance. Validation is an example of, "An applicative functor that is not a monad."
Because monad needs to process the result of computation - it needs to be able to process Left error statements, which is hard. Either monad on Left case just drops computation and returns this first Left. 
*** Applicative functions
**** liftA*
***** liftA
Essentially a [[fmap]].
#+begin_src haskell
:type liftA
liftA :: Applicative f => (a -> b) -> f a -> f b
#+end_src
***** liftA2
Lifts [[Binary][binary]] [[Function][function]] across two [[Applicative]]s [[Functor][functor]]s.
#+begin_src haskell
:type liftA2
liftA2 :: Applicative f => (a -> b -> c) -> f a -> f b -> f c
#+end_src
***** liftA2 (<*>)
liftA2 (<*>) is pretty useful. It can lift [[Binary][binary operation]] through the two layers:
It is two-layer Applicative.
#+begin_src haskell
liftA2 :: Applicative f => (    a       ->  b  ->  c ) -> f      a        ->  f    b   ->  f    c
<*> :: Applicative f =>    (f  (a -> b) -> f a -> f b)
liftA2 (<*>) :: (Applicative f1, Applicative f2) =>      f1 (f2 (a -> b)) -> f1 (f2 a) -> f1 (f2 b)
#+end_src
***** liftA2 (liftA2 (<*>))
[[liftA2 (<*>)]] 3-layer version.
***** liftA3
[[liftA2]] 3-parameter version.
** Applicative functor
Applicative functor - [[Lax monoidal functor]] with [[Tensorial strength]].
See [[Applicative]].
** Arbitrary function
Depends on type and generates values of that type.
** Arbitrary type class
[[Type class]] of [[QuickCheck]].Arbitrary (that is reexported by QuickCheck) for creating a generator/distribution of values.
Useful function is [[Arbitrary function][arbitrary]] - that autoassumes/generates values.
** Argument
arguere to make clear, to shine
argument evidence, proof

Independed variable of a function. Topic that the fuction would deal with.
Is an input value to a [[Function][function]] [[Parameter][parameter]].
** Arity
Number of [[Parameter][parameters]] of the [[Function][function]].
  * nullary - f()
  * unary   - f(x)
  * binary  - f(x,y)
  * ternary - f(x,y,z)
  * n-ary   - f(x,y,z..)
** As-pattern
#+begin_src haskell
f list@(x, xs) = ...
#+end_src
** Assertion
Statement.
Утверждение.
** Associative law
Joined by a common purpose.
$$ \forall (a,b,c) \in S : \; P(a,P(b,c)) \equiv P(P(a,b),c) $$,
Etymology:
Latin /associatus/ past participle of /associare/ "/join with/", from assimilated form of /ad/ "/to/" + /sociare/ "/unite with/", from /socius/ "/companion, ally/" from PIE /*sokw-yo-/, suffixed form of root /*sekw-/ "/to follow/".
** Base case
A part of a [[Recursion][recursive]] [[Function][function]] that trivially produces result.
** Basis
$$ \beta\alpha\sigma\iota\varsigma $$ - stepping

The initial point, unreducible axioms and terms that spawn a theory.
AKA see [[Category theory]], or Euclidian geometry basis.
** Beta normal form
No [[Beta reduction][beta reduction]] is possible.
** Beta reduction
Applying [[Function][function]] to an [[Argument][argument]].
** Binary
Two of something.
** Binary operation
$$ \forall (a,b) \in S, \exists P(a,b)=f(a,b): S \times S \to S $$
** Binary tree
#+begin_src haskell
data BinaryTree a =
    [[Leaf]]
  | [[Node]] (BinaryTree a) a (BinaryTree a)
  deriving (Eq, Ord, Show)
#+end_src
** Bind
Eq between two objects.
Parameter of the function = argument that applied to the function
Variables = values.
** Bottom value
#+begin_src haskell
-- _ fits *.
#+end_src

Is a non-value used to denote the program cannot return a values.
** Calculus of constructions
Extends the [[Curry–Howard correspondence]] to the proofs in the full intuitionistic predicate calculus (includes proofs of quantified statements).
Type theory, typed programming language, and constructivism (phylosophy) foundation for mathematics.
Directly relates to Coq programming language.
*** CoC
See [[Calculus of constructions]].
** Cardinality
Number of elements.

Number of possible implementations for a given type signature.

On sum - add cardinalities.
On product - multiply cardinalities.
** Cartesian product
${\forall a \in A, \forall b \in B : A \times B = \overset{\rightharpoonup}{(a,b)}}$.
Any function is a subset of Cartesian product.
** Case
#+begin_src haskell
case x of
    | pattern1  -> ex1
    | pattern2  -> ex2
    | pattern3  -> ex3
    | otherwise -> exDefault
#+end_src

Syntatic sugar with guards allows usage of expressions:
#+begin_src haskell
case () of _
             | expr1     -> ex1
             | expr2     -> ex2
             | expr3     -> ex3
             | otherwise -> exDefault
#+end_src

** Category
Category (/C/) consists of the [[Basis]]:
  1. Objects - ob(/C/). A node. Object of some type. Often sets, than it is [[SET category]].
  2. [[Morphism]]s - C(a,b), [[Hom-set][hom(a,b)]]. Mappings, total functions.
  3. Binary operation "Composition of morphisms": $$ \forall a, b, c : \; C(a, b) \circ C(b, c) \equiv C(a, c) $$. In other words morpisms correspond to [[Principle of compositionality]].
  4. Axiom of [[Associative law][Associativity]]: $$ f_{a \to b}, g_{b \to c}, h_{c \to d} : \; h \circ (g \circ f) \equiv (h \circ g) \circ f $$.
  5. Axiom of two sided [[Identity]] of morphisms: $\forall x \, \exists  id_{x : x \to x},  \forall f_{a \to x},  \forall g_{x \to b} : \; id_x \circ f_{a \to x} \equiv f_{a \to x}, \; g_{x \to b} \circ id_x \equiv g_{x \to b}$ (both left and right identity)

From these axioms, one can prove that there is exactly one identity morphism for every object.
*** Object
See [[Category]]
*** Category theory
See [[Category]]
** Closed-form expression
Closed-form expression - a mathematical expression that can be evaluated in a finite number of operations. It may contain constants, variables, certain "well-known" operations (e.g., + − × ÷), and functions (e.g., nth root, exponent, logarithm, trigonometric functions, and inverse hyperbolic functions), but usually no limit.
** Closed set
Closed set - a set whose complement is an open set.
Closed set is a form of [[Closed-form expression]]. Set can be closed in under a set of operations.
** Closure
Set has closure under an operation if performance of that operation on members of the set always produces a member of the same set; in this case we also say that the set is closed under the operation.
** Coalgebra
Structures that are dual (in the category-theoretic sense of reversing arrows) to unital associative [[Algebra][algebras]].
Every coalgebra, by vector space duality, reversing arrows - gives rise to an algebra. In finite dimensions, this duality goes in both directions. In infinite - it should be determined.
** CoArbitrary
Pseudogenerates a function basing on resulting type.
#+begin_src haskell
coarbitrary :: CoArbitrary a => a -> Gen b -> Gen b
#+end_src
** Codomain
Codomain - target set of a function in $X \to Y$.
** Combinator
[[Function]] without free variables.
[[Higher-order function]] that use only [[Function application][function application]] and other combinators.
#+begin_src haskell
\f g x -> f (g x)
\f g x y -> f (g x y)
#+end_src
Not comibnators:
#+begin_src haskell
\xs -> sum xs
#+end_src
Informal broad meaning: referring to the style of organizing libraries centered around the idea of combining things.
** Commutative law
$$ \forall (a,b) \in S : \; P(a,b) \equiv P(b,a) $$
** Compose
See: [[Function composition]]
** Composition
Axiom of [[Category]].
** Concatenate
Link together sequences.
** Concrete type
** Conjunction
AND
#+begin_src haskell
 * *
#+end_src
** Cons cell
Cell that values may inhabit.
** Constant
Nullary constructor
** Constraint
See: [[Ad hoc polymorphism]]
** Construct
#+begin_src haskell
(:) :: a -> [a] -> [a]
#+end_src
*** Cons
Short for [[Construct]].
** Constructor
1. [[Type constructor]]
2. [[Data constructor]]

Also see: [[Constant]]
** Contravariant
The property of basis, in which if new basis is a linear combination of the prior basis, and the change of basis inverse-proportional for the description of a [[Tensor]]s in this basisis.

Denotation:
Components for contravariant basis denoted in the upper indices:
$$ V^{i} = x $$

The inverse of a covariant transformation is a contravariant transformation. Whenever a vector should be invariant under a change of basis, that is to say it should represent the same geometrical or physical object having the same magnitude and direction as before, its components must transform according to the contravariant rule.

*** Contravariant cofunctor
See [[Contravariant]].
*** Contravariant functor
More inline term is [[Contravariant cofunctor]]
** Covariant
The property of [[Basis]], in which if new basis is a linear combination of the prior basis, and the change of basis proportional for a descriptions of [[Tensor]]s in this basisis.

Denotation:
Components for covariant basis denoted in the upper indices:
$$ V_{i} = x $$
** Covariant cofunctor
See [[Covariant]].
** Covariant functor
More inline term is [[Covariant cofunctor]]
** Curry–Howard correspondence
Computer programs are mathematical proofs.
*** Curry–Howard isomorphism
See [[Curry–Howard correspondence]].
** Currying
Translating the [[Evaluation][evaluation]] of a multiple [[Argument][argument]] function (or a tuple of arguments) into evaluating a sequence of [[Function][functions]], each with a single argument.
** Data constant
See: [[Constant]]
** Data constructor
One instance that [[Inhabit][inhabit]] [[Data type][data type]].

Constant value - nullary data constructor.
** Data declaration
[[Data type]] definition.
** data declaration
[[Data type]] declaration is the most general and versatile form to create a new data type.
Form:
#+begin_src haskell
data [context =>] type typeVars1..n
  = con1  c1t1..i
  | ...
  | conm  cmt1..q
  [deriving]
#+end_src haskell
** Data type
Data type, type.
*** Algebraic data type
Composite type formed by combining other types.
*** Higher-kinded data type
Any combination of * and ->

Type that take more types as arguments.
*** Product data type
[[Algebraic data type]] formed by logical [[Conjunction][conjunction]] (AND ' ').
*** Sum data type
[[Algebraic data type]] formed by logical [[Disjunction][disjunction]] (OR '|').
** Declaration
Top-level [[Bind][bindings]] which allow us to name [[Expression][expressions]].
** Dependent type
Type and variable have rules regarding values.

A value of a variable has a role on the resulting Type.
Or Type has rule for values.
** Derived instance
Type classes such as Eq, Enum, Ord, Show can have instances generated based definition of data type.
** Differential operator
Denotation.
$$ {d \over dx}, D, \,D_{x}}, {\displaystyle \partial _{x}}. $$
Last one is partial.

$$ e^{t{\frac {d}{dx}} $$ - [[Shift]].
*** Differential
See [[Differential operator]]
** Disjunction
OR
** Dispatch
Send, transmission, reference.
** Domain
Source set of a function in $$ X \to Y $$.
** Effect
Observable action.
** Endofunctor
Is a [[Functor][functor]] which [[Domain][domain]] and [[Codomain][codomain]] are the same [[Category][category]].
** Endofunctor category
From the name, in this [[Category]] - the objects of $$ End(C) $$ are [[Endofunctor]]s $$ F: C \to C $$, and the [[Morphism]]s are [[Natural transformation]]s between endofunctors.
** Evaluation
For FP see [[Bind]].
** Expected type
[[Data type]] [[Type inference][inferred]] from the text of the code.
** Expression
Finite combination of a symbols that is well-formed according to rules that depend on the context.
** First-class
1. Can be used as value.
2. Passed as an [[Argument][argument]].
From 1&2 -> can include itself.
** Fold
Higher-order function ruturns accumulated result from recursive data structure applying a function.
** Free variable
Variable in the fuction that is not bound by the head.
On application to the head - they are note bound to values, so fuction stays [[partial application][partially applied]].
** Function
A varying quantity depends on another quantity.

$$ x \in X, y \in Y : \; f^{X \to Y} = \overset{\rightharpoonup}{G}(x,y) $$

Directionality and property of invariability emerge from one another.
#+begin_src haskell
-- domain func codomain
   *      ->   *
#+end_src

$$ y(x) = (zx^{2} + bx + 3 | b = 5) $$
^ ^     ^^    ^    ^
| |     ||     \_Var \__Constants
| |     | \__Bound__variable
| |     \_[[Free variable][Free variable]]
|  \_[[Parameter][Parameter]]
 \__Name__of__the__function

[[Lambda abstraction]] is a function.
Function is a mathematical [[Operation][operation]].

Function = Total function = Pure function. Function theoretically posible to momoized.
[[Partial function]].
Inverse function - often partially exists (partial function).
*** Function head
Is a part with Name of the [[Function][function]] and it's [[Parameter][paramenter]].
AKA: f(x)
*** Function body
[[Expression]] that haracterizes the process.
*** Function composition
#+begin_src haskell
(.) :: (b -> c) -> (a -> b) -> a -> c

a -> (a -> b) -> (b -> c) -> c
#+end_src

In Haskell inline composition requires:
#+begin_src haskell
h.g.f $ i
#+end_src
*** Function application
Function application is applying the function to an argument from its domain to obtain the resulting value from its range.
*** Function range
The range of a function refers to either the codomain or the image of the function, depending upon usage. Modern usage almost always uses range to mean image.
So, see [[Function image]].
*** Injection
[[Function]] one-to-one injects from domain to codomain.
Keeps distinct pairing of elements of domain and image.
Every element in image coresponds to one element in domain.

$$ \forall a,b \in X, \; f(a)=f(b) \Rightarrow a=b $$

Denotion:
#+begin_src text
↣
>->
f : X ↣ Y
#+end_src
$f : X \rightarrowtail Y$

Corresponds to [[Monomorphism]].
**** Injective
See [[Injection]].
**** Injective function
See [[Injection]].
*** Surjection
[[Function]] uses codomain fully.

$$ \forall y \in Y, \exists x \in X $$

Denotation:
#+begin_src text
↠
->>
f : X ↠ Y
#+end_src
$$ f : X \twoheadrightarrow Y $$

Corresponds to [[Epimorphism]].
**** Surjective
See [[Surjection]].
**** Surjective function
See [[Surjection]].
*** Bijection
[[Function]] complete one-to-one pairing of elements of domain and codomain (image).
It means function both [[Surjection][surjective]] (so image == codomain) and [[Injection][injective]] (every domain element has unique correspondence to the image element).

For bijection inverse always exists.

Bijective operation holds the equivalence of domain and codomain.

Denotation:
#+begin_src text
⤖
>->>
f : X ⤖ Y
#+end_src
LaTeX needed to combine symbols:
$$ \newcommand{\twoheadrightarrowtail}[]{\mathrel{\rightarrowtail\kern-1.9ex\twoheadrightarrow}} \begin{document} f : X \twoheadrightarrowtail Y \end{document}} $$
**** Bijective
See [[Bijection]].
**** Bijective function
See [[Bijection]].
** Functor
Functor is a map between categories.

#+begin_src haskell
class Functor f where
  fmap :: (a -> b) -> f a -> f b
#+end_src
Functor is a type class for function application "over/through" ignored/untouched structure f.
Functor abides [[Functor laws]].
*** Functor laws
Type instance of functor should abide this laws:
1. Identity law
#+begin_src haskell
fmap id == id
#+end_src
2. Composition law
#+begin_src haskell
fmap (f.g) == fmap f . fmap g
#+end_src
In words, it is if several functions are composed and then fmap is applied on them - it should be the same as if functions was fmapped and then composed.
*** fmap
See: [[Functor]]
** Fundamental theorem of algebra
Any non-constant single-variable polynomial with complex coefficients has at least one complex root.
Also derives that the field of complex numbers is algebraically closed.
** Gen type
Generator. List it returns gets infinitely cycled.
** Girard–Reynolds polymorphic lambda calculus
See [[System F]].
** Guerrilla patch
/*/ changing code/applying patch sneakily - and possibility incompatibility with other at runtime.
[[Monkey patch]] is derivative term.
** Higher-order function
[[Function]] [[Arity][arity]] > 1.

----

Has function as a [[Parameter][parameter]].
Evaluates to function.
** Hindley–Milner type system
Classical type system for the [[Lambda calculus]] with [[Parametric polymorphism]] and [[Type inference]].
Where types marked as polymorphic variables, and overall type inference is possible all over the code.
Also known as Damas–Milner or Damas–Hindley–Milner system.
** HOF
See: [[Higher-order function]]
** Hom-set
Collection of all [[Morphism][morphisms]] from X to Y.

Denotation:
$$ hom(X,Y) $$
*** Hom-functor
For C (locally small category), its hom-functor is the functor $$ hom:C^{op} \times C \to Set $$,
from the product category of the category C wit its opposite category to the category Set of sets.

Denotation:
variants:
$$ H_A &=& \mathrm{Hom}(-, A) $$
$$ h_A &=& {\cal C}(-, A) $$
$$ Hom(A,-) : C \to Set $$

Hom-bifunctor:
$$ Hom(-,-):C^{op} \times C \to Set $$
** Idempotence
After the initial application operation can be applied multiple times without changing the result.
Example: Start and Stop buttons on machines.
** Identity
*** Two-sided identity of a [[Predicate][predicate]]
$$ P() $$ is [[Commutative][commutative]].
$$ \exist e \in S, \forall a \in S : \; P(e,a)=P(a,e)=a $$
*** Left identity of a [[Predicate][predicate]]
$$ \exist e \in S, \forall a \in S : \; P(e,a)=a $$
*** Right identity of a [[Predicate][predicate]]
$$ \exist e \in S, \forall a \in S : \; P(a,e)=a $$

Identity only possible with morphism.
There is also a distinct [[Zero]] value.
** Identity function
Return itself.
(\x.x)
#+begin_src haskell
id :: a -> a
#+end_src
** Idiom
Idiom - something having a meaning that cannot be derived from the conjoined meanings.
Meaning can be special for language speakers or human with particular knowledge.

For different meaning - it is [[Applicative functor]].
** Idiomatic
See [[Idiom]].
** Iff
If and only if, exectly when, just.
Denotation:
$$ \iff $$
** Impredicative
Self-referencing definition.

---

/Antonym - [[Predicative]]./
** Infix
Operaton in-between variables.
** Inhabit
What [[Values][values]] inhabit [[Data type][data type]]
** Initial object
Initial object - is an object I in category C: $$ \exists I \in C: \; \forall X \in C, \exists ! (I \to X) $$.
** Interface
Point of mutual meeting. Code behind interface determines how data is consumed.
** IO
Type for values whose evaluations has a posibility to cause side effects or return unpredictable result.
Haskell standard uses monad for constructing and transforming IO actions.
IO actions can be evaluated multiple times.

IO data type has unpure imperative actions inside. Haskell is pure [[Lambda calculus]], and unpure IO integrates in the Haskell purely (type system abstracts IO unpurity inside IO data type).

IO collects effects sequences one after another:
#+begin_src haskell
:{
twoBinds :: IO ()
twoBinds =
  putStrLn "First:" >>
  getLine >>=
  \a ->
  putStrLn "Second:" >>
  getLine >>=
  \b ->
  putStrLn ("\nFirst: "
    ++ a ++ ".\nSecond "
    ++ b ++ ".")
main = twoBinds
:}
#+end_src
** Kernel
Kernel of a [[Homomorphism]] is a number that measures the degree that homomorphism fails to meet [[Injective][injectivity]] (AKA be [[Monomorphic]]).
It is a number of elements that collide and fail injectivity, thou Kernel [x | x <- 0 || x >= 2].

Denotation:
$$ \operatorname{ker}T = \{ \mathbf{v} \in V:T(\mathbf{v}) = \mathbf{0}_{W} \} $$.
*** Kernel homomorphism
Morphism of elements from the [[Kernel]]. Map of elements that make main [[Morphism]] not [[Monomorphic]] ([[Injective]]).
** Kind
Kind -> Type -> Data
** Lambda abstraction
[[Lambda term]] that has a head and body and is applied to an argument.
$$ \lambda x.x+1 $$
#+begin_src haskell
\x -> x + 1
^^
#+end_src
** Lambda calculus
Universal model of computation that can be used to simulate any Turing machine.
Based on [[Function][function]] [[Abstraction][abstraction]] and [[Function application][application]] by substituting variables and [[Bind][binding]] values.

/*/ has [[Lambda term][lambda terms]]:
   * variable ($$ x $$)
   * [[Functional application][application]] ($$ (ts) $$)
   * [[Lambda function][abstraction]] ($$ (\lambda x . t) $$)
*** Lambda term
See [[Lambda calculus]]
** Lambda cube
λ-cube shows the dimentions of generalization from simply typed [[Lambda calculus]] to [[Calculus of constructions]].

Each dimension of the cube corresponds to a new way of making objects depend on other objects:
  * ([[First-class polymorphism]]) - terms allowed to depend on types, corresponding to polymorphism.
  * ([[Higher-order polymorphism]]) - types depending on terms, corresponding to dependent types.
  * ([[Type class]]) - types depending on types, corresponding to type operators.
** Lambda function
[[Function]] of [[Lambda calculus]].
$$ \lambda x y.x^2 + y^3 $$
 ^^ ^    ^
 || |     \__variable
 ||  \__variable
 || (_____)
 ||     \___BODY
 ||
 | \__parameter
  \___parameter
(___)
   \____HEAD
*** Lambda expression
See [[Lambda function]]
*** Anonymous function
See [[Lambda function]]
** Language option
Language option - control what variations of the language are permitted.
It has a set of allowed values: https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html, which can be supplied to Language [[Pragma]].
[[Lambda function]] without the name to [[Bind][bind]] to.
** Leaf
 _
** Left associative
Same level [[Exression][expression]] parts in reality follow grouping from left to right.
$$ (\lambda x . x)(\lambda y . y)z \equiv ((\lambda x . x)(\lambda y . y))z $$
** Level of code
There are mainly three levels of Haskell code.
- [[Type level]]: part that works with [[Data type][data types]]
- [[Term level]]: logical execution part of the code
- Compile level: level when code compiles/compiled
** Lexical scope
Scope search sourcecode blocks structure determined.
** Lift
Lift is to do a function application through the data structure.
** Linear type
Type system and algebra that also track the multiplicity of data.
There are 3 general linear type groups:
 * 0 - exists only at type level and is not allowed to be used at value level. Aka `s` ins ST-Trick.
 * 1 - data that is not duplicated
 * 1< - all other data, that can be duplicated multiple times.

Linear types are great to control/minimize resource usage.
** Local
[[Scope]] applies only in an area
** Magma
Set with a single binary operation.

The category of magmas, denoted $$ Mag $$, has as objects sets with a binary operation, and morphisms given by homomorphisms of operations (in the universal algebra sense).
** Module
Importable organization unit.
** Modulus
Modular arithmetic is a system of arithmetic for integers where number wraps around upon reacing a modulus.
** Monad
μόνος /monos/ sole
μονάδα /monáda/ unit

A [[Monoid]] in [[Endofunctor category]].
Monads are [[Applicative functor][applicative functors]] with natural transformation.

Mostly Monads used for sequencing actions (that looks like imperative programming), there are Commutative Monads that do not order actions.

Monadic internals are Haskell data types, so they can be consumed any number of times.

Monad can shorten/terminate sequence of computations. It is implemented inside Monad instance. For example Maybe Monad on Nothing drops chain of computation and returns Nothing.

Monad and Applicative according instances must have the same behaviour, this usually expressed in the form:
#+begin_src haskell
import Control.Monad (ap)

(<*>) == ap
#+end_src
*** Functor -> Applicative -> Monad progression
#+begin_src haskell
<$> ::     Functor f =>    (a -> b)   -> f a -> f b
<*> :: Applicative f =>   f (a -> b)  -> f a  -> f b
flip >>= ::  Monad f =>   (a -> f b)  -> f a  -> f b
#+end_src
This is [[Natural transformation]]s.
*** Monad type class
#+begin_src haskell
class Applicative m => Monad m where
  (>>=) :: m a -> (a -> m b) -> m b
  (>>) :: m a -> m b -> m b
  return :: a -> m a
#+end_src

*** Monad functions
**** Return == pure
#+begin_src haskell
return == pure
#+end_src
[[Nonstrict]].
**** Bind
#+begin_src haskell
>>= :: Monad f => f a -> (a -> f b) -> f b
#+end_src
[[Nonstrict]].

The most ubiqutous way to >>= something is to use [[Lambda function]]:
#+begin_src haskell
getLine >>= \name -> putStrLn "age pls:"
#+end_src

Also very neet way is to bundle and handle Monad - is to bundle it with bind, and leave applied partially.
And use that partial bundle as a function - every evaluation of the function would trigger evaluation of internal Monad structure. Thumbs up. 
#+begin_src haskell
printOneOf ∷ Bool → IO ()
printOneOf False = putStr "1"
printOneOf  True = putStr "2"

quant ∷ (Bool → IO b) → IO b
quant = (>>=) (randomRIO (False, True))

recursePrintOneOf ∷ Monad m ⇒ (t → m a) → t → m b
recursePrintOneOf f x = (f x) >> (recursePrintOneOf f x)

main ∷ IO ()
main = recursePrintOneOf (quant) $ printOneOf
#+end_src
***** (>>=)
See [[Bind]]
**** Join
#+begin_src haskell
join :: Monad m => m (m a) -> m a
#+end_src
Flattens two layers of structure into one.
Join is a generalization of `concat`.

The way to express ordering in lambda calculus is to nest.
***** join.fmap == (=<<)
#+begin_src haskell
-- b = f b
fmap      :: Monad f => (a -> f b) -> f a -> f (f b)
join      :: Monad f =>                      f (f a) -> f a
join.fmap :: Monad f => (a -> f b) -> f a            -> f b
flip >>=  :: Monad f => (a -> f b) -> f a            -> f b
#+end_src

**** Sequencing operator (>>) == (*>):
Discards any resulting value of the action and sequence next action.
#+begin_src haskell
(>>) :: m a -> m b -> m b
(*>) :: f a -> f b -> f b
#+end_src
Applicative has a similar operator.
*** Monad OR Applicative
**** Start writing monad using 'return', 'ap', 'liftM', 'liftM2', '>>' instead of 'do','>>='
If you wrote code and really needed only those - move that code to Applicative.
#+begin_src haskell
return -> pure
ap -> <*>
liftM -> liftA -> <$>
>> -> *>
#+end_src
**** Basic case when Applicative can be used
Can be rewriten in [[Applicative]]:
#+begin_src haskell
func = do
  a <- f
  b <- g
pure (a, b)
#+end_src

Can't be rewritten in [[Applicative]]:
#+begin_src haskell
somethingdoSomething' n = do
a <- f n
b <- g a
pure (a, b)
#+end_src
(f n) creates monadic structure, binds ot to /a/ wich is consumed then by g.
**** Applicative block vs Monad block
With Type Applicative every condition fails/succseeds independently. It needs a boilerplate data constructor/value pattern matching code to work. And code you can write only for so many cases and types, so boilerplate can not be so flexible as Monad that allows polymorphism.
With Type Monad computation can return value that dependent from the previous computation result. So abort or dependent processing can happen.
*** Maybe monad
Drops the chain of computation and returns Nothing as soon as Nothing arrives.
*** Either monad
Drops sequencing computation as soon as Left arrives.
*** Monad laws
**** Left identity law
#+begin_src haskell
return x >>= f == f x
#+end_src
**** Right identity law
#+begin_src haskell
m >>= return == m
#+end_src
**** Associativity law
#+begin_src haskell
(m >>= f) >>= g == m >>= (\x -> f x >>= g)
#+end_src
** Monkey patch
/From [[Guerrilla patch]]./

/*/ is a way for program to modify supporting system software affecting only the running instance of the program.
** Monoid
[[Semigroup]] that has [[Identity]] value.

#+begin_src haskell
class Monoid m where
mempty :: m
mappend :: m -> m -> m
mconcat :: [m] -> m
mconcat = foldr mappend mempty
#+end_src
*** Monoid laws
Left identity:
#+begin_src haskell
mempty <> x = x
#+end_src

Right identity:
#+begin_src haskell
x <> mempty = x
#+end_src

Associativity:
#+begin_src haskell
x <> mempty = x (y <> z) = (x <> y) <> z
mconcat = foldr (mempty <>)
#+end_src
*** Commutative monoid
Commutative law:
$$ x \circ y = y \circ x $$
Very helpful at concurrent or distributed processing.
**** Abelian monoid
See [[Commutative monoid]]
** Monoidal functor
Functors between [[Monoid][monoidal]] [[Category][categories]] that preserves monoidal structure.
** Morphism
μορφή /morphe/ form
Map between two objects in an abstract [[Category][category]].

Morphism is a generalization ($$ f(x*y) \equiv f(x) \diamond f(y) $$) of [[Homomorphism]] ($$ f(x*y) \equiv f(x) * f(y) $$).
Under morphism almost always mean homomorphism-like properties.

If some morphism corresponds to function requirements - than it is a [[Function]].
*** Homomorphism
ὁμός /homos/ same (chosen by initial Anglish mistranslation "similar")
μορφή /morphe/ form
similar form

Homomorphism is a map between two algebraic structures of the same type, that preserves the operation of the structures.
This means a map $$ f:A\to B $$ between two sets $$ A, B $$ equipped with the same structure such that, if $$ ∗ $$ is an operation of the structure (supposed here, for simplification, to be a binary operation), then $$ f(x*y)=f(x)*f(y) $$.

The concept of homomorphism has been generalized under the name of [[Morphism][morphism]] to many other structures that either do not have an underlying set, or are not algebraic.

Homomorphisms send identities to identities and inverses to inverses.
Homomorphism preserves operations, as such:
'*' homomorphism - map between '*' and preserves '*' operations
  (which can be):
  * semigroup
  * monoid
  * groups
  * ring
  * linear map
  * module
  * algebra
*** Identity morphism
Identity morphism - or simply identity: $$ x \in C : \; id_{x}=1_{x} : x \to x $$
Composed with other morphism gives same morphism.
*** Monomorphism
μονο /mono/ only
μορφή /morphe/ form

Initial set of /f/ is fully uniquely mapped onto the image of /f/.
Left is mono (uniquely) mapped to the right, so left [[Domain][domain]] can be equal or less to the right [[Codomain][codomain]].
It is [[Injection][injective]].
It always has a inverse morphism.

$$ f^{X \to Y}, \forall x \in X \, \exists y=f(x) \vDash f(x) = f_{mono}(x) $$ - from [[Homomorphism]] context
$$ f_{mono} \circ g1 \equiv f_{mono} \circ g2 \vDash \; g1 \equiv g2 $$ - from general [[Morphism]] context
Thus it is left canselable.
**** Monomorphic
See [[Monomorphism]].
*** Epimorphism
επι /epi/ on, over
μορφή /morphe/ form

Image fully uses codomain - epimorphism.
It is surjective.

$$ f^{X \to Y}, \forall y \in Y \, \exists f(x) \vDash f(x)=f_{epi}(x) $$ - from [[Homomorphism]] context
$$ g_1 \circ f_{epi} \equiv g_2 \circ f_{epi} \vDash \; g_1 = g_2 $$ - from general [[Morphism]] context
Thus it is right canselable.

Left is epi to the right. So left is bigger or equal then the right. And right is a projection of the left.
**** Epimorphic
See [[Epimorphism]].
*** Isomorphism
ἴσος /isos/ equal
μορφή /morphe/ form

Morphism that has inverse morphism.
[[Bijection][Bijective]] [[Homomorphis][homomorphism]] is also isomorphism.

$$ f^{-1, b \to a} \circ f^{a \to b} \equiv id^a, \; f^{a \to b} \circ f^{-1, b \to a} \equiv id^b $$

2 reasons for non-isomorphism:
- function at least ones collapses a values of domain into one value in codomain
- image (of a function in codomain) does not fill-in codomain. Then isomorphism can exists for image but not whole codomain.
**** Isomorphic
See [[Isomorphism]].
*** Endomorphism
ενδο /endo/ internal
μορφή /morphe/ form

Morphism whose [[Domain][domain]] equals the [[Codomain][codomain]].
Epimorphism is a [[Monoid]], because of [[Catogoty]] [[Composition]].
**** Automorphism
[[Endomorphism]] that is [[Isomorphism]].
*** Catamorphism
κατά /kata/ downward
μορφή /morphe/ form

Denotes the unique [[Homomorphism][homomorphism]] from an initial algebra into some other algebra.

In functional programming, catamorphisms provide generalizations of folds of lists to arbitrary algebraic data types, which can be described as initial algebras. The dual concept is that of anamorphism that generalize unfolds. A hylomorphism is the composition of an anamorphism followed by a catamorphism.
** Natural transformation
Natural transformation provides a way of transforming one [[Functor]] into another while respecting the internal structure (i.e., the [[Composition]] of [[Morphism]]s) of the [[Category][categories]] involved.
Natural transformation is a "morphism of functors", especially in functor categories.

** newtype declaration
Creates a new type from old type using a new constructor.
#+begin_src haskell
newtype FirstName = FirstName String
#+end_src haskell

Data will have exactly the same representation at runtime, as the type that is wrapped.

#+begin_src haskell
newtype Book = Book (Int, Int)
#+end_src haskell
#+begin_src text
      (,)
      / \
Integer Integer
#+end_src
** Node
#+begin_src text
 *
/ \
#+end_src
** NonEmpty list data type
Data.List.NonEmpty
Has a Semigroup instance but can't have a Monoid instance. It never can be an empty list.

#+begin_src haskell
data NonEmpty a = a :| [a]
  deriving (Eq, Ord, Show)
#+end_src haskell

:| - an infix data costructor that takes two (type) arguments. In other words :| returns a product type of left and right
** Normal form
In context: [[Beta normal form]]
** Nothing
Any Haskell expression can't return nothing.
** Open formula
[[Function]] with [[Arity][arity]].
** Operation
As also called [[Function][function]].
Used in mathematics. Word often used for [[Infix][infix]] operations.
** Operator
[[Infix]] [[Function][function]].
** Orphan type instance
[[Type instance]] that appeared from inconsistent code base. Duplicate of instance, or instance present on [[Type class][type class]] or on [[type]] level.

Solution for addressing orphan instances:
1. You defined the type but not the type class?
Put the instance in the same module as the type so that the type cannot be imported without its instances.
2. You defined the type class but not the type?
Put the instance in the same module as the type class definition so that the type class cannot be imported without its instances.
3. Neither the type nor the type class are yours?
Define your own newtype wrapping the original type and now you’ve got a type that “belongs” to you for which you can rightly define type class instances. There are means of making this less annoying which we’ll discuss later.
** Parameter
παρά /para/ subsidiary
μέτρον /metron/ measure

Or Formal Parameter - named varible of a [[Function][function]].
Is variable defined in function definition.
Contrary to the [[Argument]] wich is a supplied value to a function.
** Partial application
Part of [[Function][function]] [[parameter][parameters]] [[Application][applied]].
** Partial function
Does not cover all cases.
Unsafe and causes trouble.
** Permutation
[[Bijective]] [[function]] from [[Domain][domain]] to itself.
** Point-free
/Use Tacit very carefully - it hides types and harder to change code where it is used./
/Use just anough Tacit to communicate better. Mostly only partial point-free communicates better./

Point-free style, is a paradigm in which functions only describe the [[Morphism]] itself.
If brackets /()/ can be changed to /$/ then $ equal to [[Composition]]:
#+begin_src haskell
\x -> g (f x)
\x -> g $ f x
\x -> g . f $ x
\x -> g . f -- eta-recution

\x1 x2 -> g (f x1 x2)
\x1 x2 -> g $ f x1 x2
\x1 x2 -> g . f x1 $ x2
\x1    -> g . f x1
#+end_src
*** \eta-abstraction
$$ (\lambda x.Mx) \xleftarrow[\eta]{} M $$
**** Synonims
***** \eta-reduction
See [[\eta-abstraction]]
***** \eta-conversion
See [[\eta-abstraction]]
***** eta-abstraction
See [[\eta-abstraction]]
***** eta-reduction
See [[\eta-abstraction]]
***** eta-conversion
See [[\eta-abstraction]]
*** (.).(.)
#+begin_src haskell
(.).(.) :: (b -> c) -> (a -> a1 -> b) -> a -> a1 -> c
#+end_src

Composition of compositions =(.).(.)= allows to compose =f1(c) . f2(a,b)=. During composition allows to apply two arguments to a binary function.
#+begin_src haskell
\f g x y -> f (g x y)
#+end_src
**** .) .
**** Sectioning
See [[(.).(.)]]
**** Blackbird
See [[(.).(.)]]
*** Point-free becomes better in multi-dimentional data
BigData and OLAP analysis.
*** Synonims
**** Pointfree
See [[Point-free]]
**** Tacit
See [[Point-free]]
**** Tacit programming
See [[Point-free]]
*** Swing
#+begin_src haskell
swing :: (((a -> b) -> b) -> c -> d) -> c -> a -> d
swing = flip . (. flip id)
swing f = flip (f . runCont . return)
swing f c a = f ($ a) c
#+end_src
*** Squish
#+begin_src haskell
f >>= a . b . c =<< g
#+end_src

** Polymorphism
At once several forms.

To [[Abstraction][abstract]] over [[Data types][data types]].


/Antonym - [[Monomorphism]]./

Types:
*** Levity polymorphism
Levity polymprphism is when polymorphism works with lifted and [[Unlifted type][unlifted types]].
*** Parametric polymorphism
[[Abstraction][Abstracting]] over [[Data type][data types]] by [[Parameter][parameter]].

/In most languages named as 'Generics' (generic programming)./

Types:
**** Let-bound polymorphism
It is property chosen for Haskell type system.
Haskell is based on Hindley-Milner type system, it is let-bound.
It means that to have strict [[Type inference][type inference]] - if `let` and `where` declarations a polymorphic - $\lambda$ declarations - should be not.
So:
#+begin_src haskell
foo :: (Int, Char)
foo = (\f -> (f 1, f 'a')) id
#+end_src
Is illegal in Haskell.

Lambda-bound function (i.e., one passed as argument to another function) cannot be instantiated in two different ways, if there is a let-bound polymorphism.
**** Constrained polymorphism
Constrained [[Parametric polymorphism]].
**** First-class polymorphism
More default term: [[Impredicative polymorphism]].
**** Impredicative polymorphism
The most powerful form of [[Parametric polymorphism]].
First see [[Impredicative]].

Impredicative polymorphism allows type τ entities with polymorphic types, that can contain type τ itself.
$$ T = \forall X. X \to X : \; T \in X \vDash T \in T $$
This approach has Russell's paradox (and its form - Girard's paradox).
*** Ad hoc polymorphism
Artificial [[Polymorphism][polymorphism]] dependent on incoming [[Data type][data type]].
Achieved by creating a [[Type class][type class]] [[Function][functions]].
It is interface dispatch mechanism by data types.

/Commonly known as overloading./
*** Subtype polymorphism
Allows to declare usage of a Type and all of its Subtypes.
T - Type
S - Subtype of Type
<: - subtype of
$$ S <: T = S \le T $$

Subtyping is:
If it can be done to T, and there is subtype S - then it also can be done to S.
$$ S <:T : \; f^{T \to X} \Rightarrow f^{S \to X} $$
*** Row polymorphism
# NOTE: 2019-03-11: Currently WIP in https://github.com/ghc-proposals/ghc-proposals/pull/180 
Is a lot like Subtype polymorphism, but alings itself on allowence (with | r) of subtypes and types with requested properties.
#+begin_src haskell
printX :: { x :: Int | r } -> String
printX rec = show rec.x

printY :: { y :: Int | r } -> String
printY rec = show rec.y

-- type is inferred as `{x :: Int, y :: Int | r } -> String`
printBoth rec = printX rec ++ printY rec
#+end_src
*** Kind polymorphism
Achieved using a phantom type argument in the data type declaration.
#+begin_src haskell
;;         * -> *
data Proxy a = ProxyValue
#+end_src
Then, by default the data type can be inhabited and fully work being partially defined.
But multiple instances of kind polymorphic type can be distinguished by their particular type.

Example is the [[Proxy type]]:
#+begin_src haskell
data Proxy a = ProxyValue

let proxy1 = (ProxyValue :: Proxy Int) -- * :: Proxy Int
let proxy2 = (ProxyValue :: Proxy a)   -- * -> * :: Proxy a
#+end_src

*** Higher-rank polymorphism
Means that polymorphic types can apper within other types (types of funtion).
There is a cases where higher-rank polymorphism than the a Ad hoc - is needed. For example where ad hoc polymorphism is used in constraints of several different implementations of functions, and you want to build a function on top - and use the abstract interface over these functions.
#+begin_src haskell
-- ad-hoc polymorphism
f1 :: forall a. MyType Class a => a -> String
f1 = -- ...

-- higher-rank polymorphism
f2 :: Int -> (forall a. MyType Class a => a -> String) -> Int
f2 = -- ...
#+end_src
By moving `forall` inside the function - we can achive higher-rank polymorphism.

From: https://news.ycombinator.com/item?id=8130861
#+begin_src text
Higher-rank polymorphism is formalized using System F, and there are a few implementations of (incomplete, but decidable) type inference for it - see e.g. Daan Leijen's research page [1] about it, or my experimental implementation [2] of one of his papers. Higher-rank types also have some limited support in OCaml and Haskell.
#+end_src

Useful example aslo a [[ST-Trick monad]].
*** Linearity polymorphism
Leverages [[Linear type][linear types]].
For exampe - if fold over a dynamic array:
  1) In basic Haskell - array would be copied at every step.
  2) Use low-level unsafe functions.
  3) With Linear type function we guarantee that the array would be used only at one place at a time.

So, if we use a function (* -o * -o -o *) in foldr - the fold will use the initial value only once.
** Pragma
Pragma - instruction to the compiler placed in the source code that specifies how a compiler should process the code.
Pragma in Haskell have form:
#+begin_src haskell
{-# PRAGMA options #-}
#+end_src
** Pragma
*** LANGUAGE pragma
**** LANGUAGE options
***** Useful by default
#+begin_src haskell
import EmptyCase
import FlexibleContexts
import FlexibleInstances
import InstanceSigs
import MultiParamTypeClasses
#+end_src
***** GeneralisedNewtypeDeriving
Allows `deriving` to inherit any instances of representation type.
#+begin_src haskell
newtype Dollars = Dollars Int
  deriving (Eq, Ord, Show, Read, Enum, Num, Real, Bounded, Integral)
#+end_src
This is all instances `Int` has.

In Haskell98 only Eq, Ord, Enum could been inherited.
***** TypeApplications
Allows to use visible type application in expressions.
A visible type application is preceded with an @ sign.

#+begin_src haskell
:type pure @[]
pure @[] :: a -> [a]

:type (<*>) @[]
(<*>) @[] :: [a -> b] -> [a] -> [b]

--

instance (CoArbitrary a, Arbitrary b) => Arbitrary (a -> b)

λ> ($ 0) <$> generate (arbitrary @(Int -> Int))
    12
#+end_src
***** FlexibleInstances
**** How to make a GHC LANGUAGE extension
In `libraries/ghc-boot-th/GHC/LanguageExtensions/Type.hs` add new constructor to the `Extension` type
#+begin_src haskell
data Extension
  = Cpp
  | OverlappingInstances
  ...
  | Foo
#+end_src

`/main/DynFlags.hs` extend `xFlagsDeps`:
#+begin_src haskell
xFlagsDeps = [
  flagSpec "AllowAmbiguousTypes" LangExt.AllowAmbiguousTypes,
  ...
  flagSpec "Foo"                 LangExt.Foo
]
#+end_src
It is for basic case. For testing, parser see further: https://blog.shaynefletcher.org/2019/02/adding-ghc-language-extension.html
** Pragma option
Values supplied to the [[Pragma]] directive.
** Predicate
[[Assertion]] includes variable.
Notation: $$ P(x) $$
[[Application]] of [[Argument][argument]] results in true or false predicate.
** Predicative
Non-self-referencing definition.

---

/Antonym - [[Impredicative]]./
** Principal type
The most generic [[Data type][data type]] that still typechecks.
** Principle of compositionality
The meaning of a complex [[Expression][expression]] is determined by the meanings of its constituent expressions and the rules used to combine them.
** Proxy type
Proxy type holds no data, but has a phantom parameter of arbitrary type (or even kind). Able to provide type information, even though has no value of that type (or it can be may too costly to create one).
#+begin_src haskell
data Proxy a = ProxyValue

let proxy1 = (ProxyValue :: Proxy Int) -- a has kind `Type`
let proxy2 = (ProxyValue :: Proxy List) -- a has kind `Type -> Type`
#+end_src
** \Psi-combinator
Applies function to two different structures, then chains binary function and returns a result.
#+begin_src haskell
import Data.Function (on)
on :: (b -> b -> c) -> (a -> b) -> a -> a -> c
#+end_src
*** Psi-combinator
See: [[\Psi-combinator]]
*** On-combinator
See: [[\Psi-combinator]]
** Purity
[[Referantial transparency][Referential transparent]] [[Function][function]]
** Quantifier
Specifies the quantity of specimens.

Two most common quantifiers $$ \forall $$ and $$ \exists $$.
** Recursion
Repeated function application allow computing results that may require indefinite amount of work.
** Redex
[[Reduction][Reducible]] [[Expression][expression]]
** Reduction
See [[Beta Reduction]]
** Referential transparency
Function returns the same output given the same values to evaluate.

[[Expression]] is referentially transparent if can be replaced with its corresponding resulting value without change for program's behavior.
Such [[Functions][functions]] are called [[Pure][pure]].
** Relation
Is not directed and not limited.
** REPL
Interactive CLI. Read-eval-print loop.
** Scope
Area where [[Bind][bind]] is accessible.
** Sectioning
Writing [[Function][function]] in a parentheses. Allows to pass around [[Partial application][partially applied]] [[Function][functions]].
** Semantics
Philosophical study of meaning.
*** Operational semantics
Properties, such as correctness, safety or security, are verified by constructing proofs from logical [[Assertion][statements]] about execution and procedures.

Good to solve in-point localized tasks.
Process of abstraction.
*** Denotational semantics
Constructing mathematical objects (called denotations), that describe the meanings.

Good to achive more broad approach/meaning.
Also see [[Abstraction]].
*** Axiomatic semantics
Describing effect of operation on assertions about the overall state.

Good for examining interconnections.
Empirical process.
** Semigroup
$$ \forall (a,b,c) \in S : \; P(a,P(b,c)) \equiv P(P(a,b),c) $$

Semigroup - [[Magma]] with [[Associative law][associative law]].
Semigroup is closed (forms a closed set).

Defined in Haskell as:
#+begin_src haskell
class Semigroup a where
(<>) :: a -> a -> a
#+end_src

** Set
Well-defined collection of distinct objects.
** SET category
[[Category]] in which [[Object][objects]] are sets.
** Shadowing
Global scope variable overriden by variable in local scope.
** Shift operator
Shift operator defined by Lagrange through Differential operator.
$$ \displaystyle T^{t}=e^{t{\frac {d}{dx}}} $$
*** Shift
See [[Shift operator]]
** Shrinking
Process of reducing coplexity in the test case - re-run with smaller values and make sure that the test still fails.
** Singleton
Singleton - unit set - set with exactly one element.
Also 1-tuple.
** Smart constructor
Place extra constraints on the construction of values.
** Spine
#+begin_src text

  :
 / \
1   :
   / \
  2   :
     / \
    3  []

1:2:3:[]

  :
 / \
_   :
   / \
  _   :
     / \
    _  []

#+end_src
** Statement
Declarative sentence that is true or false.
Gonzales: "What code does."
** Static typing
Static typechecking occurs at [[Level of code][compile time]]
** Structural type
Is a type in the real mathematical sence, in the Structural Type System.
The Structural Type System differentiate and compares the types basing on their properties. So all structural types have a global hierarchy of properties, types and subtypes.
Like in Haskell.
In most languages typing is not structural - but name-based.
** Superclass
Broader parent class.
** Syntatic sugar
Artificial way to make language easier to read and write.
** System F
Formalizes the notion of parametric polymorphism in programming languages.
Differs from the simply typed lambda calculus by the introduction of universal [[Quantifier][quantification]] over types.
** Tail call
Final result of the function
** Tail recursion
Tail calls are recursive invocantions of itself.
** Tensor
Object existing out of planes, thus it can translate objects from one plane into another.
They can be tried to be described with knowledge existing inside planes, but representation would always be partial, aka [[Ambigram]].
Tensor of rank 1 is a vector.

Tensors can be seen as [[Functor]]s.
** Terminal object
Terminal object - is an object I in category C: $$ \exists I \in C : \; \forall X \in C, \, \exists ! (X \to I) $$.
** Term level
See: [[Level of code]]
** Testing
*** Property testing
Since [[Property][property]] has a law, then family of that unit tests can be abstracted into the [[Lambda function][lambda function]].
And tests cases come from [[Generator][generator]].
**** Property
Property corresponds to the according law.
In property testing you need to think additionally about [[Generator][generator]]s and [[Shrinking][shrinking]].
**** Property testing types
|--------------------------+--------------------------------------+--------------------------------------+---------------------------|
|                          | Exhaustive                           | Randomized                           | Unit test (Single sample) |
|--------------------------+--------------------------------------+--------------------------------------+---------------------------|
| Whole set of values      | Exhaustive property test             | Randomised property test             |                           |
| Special subset of values | Exhaustive specialised property test | Randomised specialised property test |                           |
|--------------------------+--------------------------------------+--------------------------------------+---------------------------|
**** Generator
#+begin_src text
Seed
|
v
Gen A -> A
^
|
Size
#+end_src

Seed allows reproducibility.
There is anyway a need to have some seed.
Size allows setting upper bound on size of generated value. Think about infinity of list.

After failed test - shrinking tests value parts of contrexample, finds a part that still fails, and recurses shrinking.
***** Custom generator
When sertain theorem only works for a specific set of values - the according generator needs to be produced.

#+begin_src haskell
arbitrary :: Arbitrary a => Gen a
suchThat :: Gen a -> (a -> Bool) -> Gen a
elements :: [a] -> Gen a
#+end_src
**** Reusing test code
Often it is convinient to abstract testing of same function properties:

It can be done with (aka TestSuite [[Combinator][combinator]]):
#+begin_src haskell
-- Definition
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE AllowAmbiguousTypes #-}
eqSpec :: forall a. Arbitrary a => Spec

-- Usage
{-# LANGUAGE TypeApplications #-}
spec :: Spec
spec = do
  eqSpec @Int
#+end_src

#+begin_src haskell
Eq Int
  (==) :: Int -> Int -> Bool
    is reflexive
    is symetric
    is transitive
    is equivalent to (\ a b -> not $ a /= b)
  (/=) :: Int -> Int -> Bool
    is antireflexive
    is equivalent to (\ a b -> not $ a == b)
#+end_src
***** Commutativity
#+begin_src haskell
:: Arbitrary a => (a -> a -> a) -> Property
#+end_src
***** Symmetry
#+begin_src haskell
:: Arbitrary a => (a -> a -> Bool) -> Property
#+end_src
***** Equivalence
#+begin_src haskell
:: (Arbitrary a, Eq b) => (a -> b) -> (a -> b) -> Property
#+end_src
***** Inverse
#+begin_src haskell
:: (Arbitrary a, Eq b) => (a -> b) -> (b -> a) -> Property
#+end_src

**** QuickCheck
`SomethingSomething` is a member of the Arbitrary type class.
`SomethingSomething -> Bool` is something `Testable`.
Generator `arbitrary`, gets the seed, and generates.
`quickCheck` runs the loop and tests.
*** Write tests algorithm
1. Pick the right language/stack to implement features.
2. How expensive breakage can be.
3. Pick the right tools to test this.
** Tuple
Data type that stores multiple values withing a single value.
Tuples by [[Arity][arity]]:
  * empty, [[Unit][unit]]          - 0
  * pair, two-tuples     - 2
  * thriple, three-tuple - 3
** Type
Type - [[Set][set]] of values.
See [[Data type]]
** Type alias
Create new type constructor, and use all data structure of base type.
** Type class
Type system construct that adds a support of [[Ad hoc polymorphism][ad hoc polymorphism]].
** Type class inheritance
[[Type class]] has a [[Superclass][superclass]].
** Type constant
See: [[Constant]]
** Type constructor
Name of [[Data type][data type]]

Nullary type constructor is [[Type constant]]
** type declaration
Synonim for existing type. Uses the same data constructor.
#+begin_src haskell
type FirstName = String
#+end_src haskell
Used to distinct one entities from other entities, while they have the same type.
Also main type functions can operate on a new type.
** Type inference
Automatic [[Data type][data type]] detection of [[Expresion][expression]].
** Type instance
Unique [[Type class][type class]]->[[Data type][type]] pairing.
Defines type class->type methods.
** Type level
See: [[Level of code]]
** Type variable
Refer to an unspecified type in Haskell type signature.
** Uncurry
Replace number of [[Function][functions]] with [[Tuple][tuple]] of number of values
** Undefined
Value helps to do typechecking
** Unit
Value, [[Data type][type]]. Represents nothing. Empty [[Tuple][tuple]]
** Unlifted type
Type that directly exist on the hardware. The type abstraction can be completely removed.
With unlifted types Haskel type system directly manages data in the hardware.
** Unsafe
[[Function]] that does not cover some edge case.
** Variable
A name for [[Expression][expression]].

Haskell has immutable variables.
Except when you hack it with explicit [[Function][funсtions]].
** Variadic
Variadic funtion has a indefinite [[Arity][arity]]. Assepts a variable number of [[Argument][arguments]].
** Zero
Zero is the value operation with which always gives Zero value.
$n, zero \in C : \forall n, zero*n=zero$
There is also distinct [[Identity]] value.
* Give definitions
** Kleisli category
** Free object
** Thin category
** Partial order
** Total order
** Preorder
** Identity type
** Constant type
** Arbitrary
** Gen
** Context
aka
#+begin_src haskell
Eq a => a -> Set a -> Set a
#+end_src
** ST-Trick monad
ST is like a lexical scope, where all the variables/state disappear when the function returns
https://wiki.haskell.ohttps://www.schoolofhaskell.com/school/to-infinity-and-beyond/older-but-still-interesting/deamortized-strg/Monad/ST
https://dev.to/jvanbruegge/what-the-heck-is-polymorphism-nmh
** Lax monoidal functor
** Tensorial strength
** Strong monad
* Citations
"One of the finer points of the Haskell community has been
its propensity for recognizing abstract patterns in code which
have well-defined, lawful representations in mathematics." (Chris Allen, Julie Moronuki - "Haskell Programming from First Principles" (2017))
* Good code
** Type aliasing
Use data type aliases to deferentiate logic of values.
** Type wideness
Parametric polymorphism is broader then constrained polymorphism
Unconstrained means most flexible, but the most useless.
The more constrained system has more usefulness.
** Read Conventions of variables (page 176)
** Print
print :: Show a => a -> IO ()
print a = putStrLn (show a)
** Read code evaluation (488 on-ward)
** Fold
foldr spine recursion intermediated by the folding
foldl spine folding is unconditional, then solding starts.

So foldr can terminate at any point, while foldl unconditionally recurses across the spine, even if it infinite.
** Computation model
Model the domain and types before thinking about how to write computations.
** Make bottoms only local
** Newtype wrap is ideally transparent for compiler and does not change performance
** Instances of types/type classes must go with code you write
** Functions can be abstracted as arguments
** Infix operators can be bind to arguments
** Arbitrary
Product types can be tested as a product of random generators.
Sum types require to implement generators with separate constructors, and picking one of them, use `oneof` or `frequency` to pick generators.

** Principle of Separation of concerns
** Function composition
In Haskell inline composition requires:
#+begin_src haskell
  h.g.f $ i
#+end_src
Function application has a higher priority than composition. That is why parentheses over argument are needed.
This precedence allows idiomatically compose partially applied functions.

But it is a way better then:
#+begin_src haskell
  h (g (f i))
#+end_src
** Functor application
Function application on n levels beneath:
#+begin_src haskell
(fmap.fmap) function twoLevelStructure
#+end_src

How fmap.fmap typechecks:
#+begin_src haskell
(.) :: (b -> c) -> (a -> b) -> a -> c
fmap :: Functor f => (m -> n) -> f m -> f n
fmap :: Functor g => (x -> y) -> g x -> g y

(.) :: (Functor f, Functor g)
  => ((g x -> g y) -> f.g (x) -> f.g (y))
  -> ((x -> y) -> g x -> g y)
  -> (x -> y) -> f.g (x) -> f.g. (y)
fmap.fmap :: (x -> y) -> f.g (x) -> f.g. (y)
#+end_src
** Parameter order
In functions parameter order is important.
It is best to use first the most reusable parameters.
And as last one the one that can be the most variable, that is important to chain.
** Applicative monoid
There can be more then one valid Monoid for a data type. &&
There can be more than one valid Applicative instance for a data type. ->
There can be differnt Applicatives with different Monoid implementations.
** Creative process
*** Pick phylosophy principles one to three the more - the harder the implementation
*** Draw the most blurred representation
*** Deduce abstractions and write remotely what they are
*** Model of computation
**** Model the domain
**** Model the types
**** Think how to write computations
*** Create
* Useful functions to remember
** Prelude
#+begin_src haskell
enumFromTo
enumFromThenTo
reverse
show :: Show a => a -> String
flip
sequence - Evaluate each monadic action in the structure from left to right, and collect the results.
:sprint - show variables to see what has been evaluated already.
minBound - smaller bound
maxBound - larger bound
cycle :: [a] -> [a] - indefinitely cycle s list
repeat - indefinit lis from value
elemIndex e l - return first index, returns Maybe
fromMaybe (default if Nothing) e ::Maybe a -> a
lookup :: Eq a => a -> [(a, b)] -> Maybe b
#+end_src
*** Ord
compare
*** Calc
div - always makes rounding down, to infinity
divMod - returns a tuple containing the result of integral division and modulo
*** List operations
#+begin_src haskell
concat - [ [a] ] -> [a]
elem x xs - is element a part of a list
zip :: [a] -> [b] -> [(a, b)] - zips two lists together. Zip stops when one list runs out.
zipWith :: (a -> b -> c) -> [a] -> [b] -> [c] - do the action on corresponding elements of list and store in the new list
#+end_src
** Data.List
#+begin_src haskell
intersperse :: a -> [a] -> [a]  -  gets the value and incerts it between values in array
nub - remove duplicates from the list
#+end_src
** Data.Char
#+begin_src haskell
ord (Char -> Int)
chr (Int -> Char)
isUpper (Char -> Bool)
toUpper (Char -> Char)
#+end_src
** QuickCheck
#+begin_src haskell
quickCheck :: Testable prop => prop -> IO ()

quickCheck . verbose - run verbose mode
#+end_src

* Investigate
** Control.Monad
* Debugger

Provides:
  * set a breakpoints
  * observe step-by-step evaluation
  * tracing mode

** Commands
:list

** Breakpoints
:break 2
  :show breaks
  :delete 0
:continue

** Step-by-step
:step main
** What been evaluated already
:sprint name
* Tools
** Search over the Haskell packages code: Codesearch from Aelve
https://codesearch.aelve.com/
* Libs
** Parsers - megaparsec
** CLIs - optparse-applicative
** HTML - Lucid
** Web applications - Servant
* Misc
